version: '3'
services:
  web:
    image: 'node:10-alpine'
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ".:/app"
    working_dir: /app  
    command: 'npm run start'
